POST http://localHost:3001/users/login
Content-Type: application/json

{
    "username": "Jim",
    "password": "J"
}

###

POST http://localHost:3001/users/signup
Content-Type: application/json

{
    "firstName": "msdfa",
    "lastName": "bdkd",
    "Email": "bball@gmail.com",
    "username": "Gsmith",
    "password": "m3234!dfkjd"
}

###

POST  http://localHost:3001/tasks/task-list
Content-Type: application/json

{
    "userID": "6435bd95c24a1f9badf71eee",
    "currentDate": "04/17/2023"
}

###

POST http://localHost:3001/tasks/create 
Content-Type: application/json

{
    "name": "work", 
    "time": "11:00 am", 
    "points": "6", 
    "date": "04/17/2023", 
    "userID": "6435bd95c24a1f9badf71eee"
}

###

DELETE http://localHost:3001/tasks/delete 
Content-Type: application/json

{
    "taskID": "644b6fba3e98cdfec61f4f15", 
    "date": "04/17/2023", 
    "userID": "6435bd95c24a1f9badf71eee"
}

###

PUT http://localHost:3001/tasks/update
Content-Type: application/json

{
    "name"   : "pool",
    "time"   : "9:00 am",
    "points" : "20",
    "isChecked" : true,
    "userID" : "6435bd95c24a1f9badf71eee",
    "taskID" : "644b6a9bc67eafc3717be7be"
}

###

GET http://localHost:3001/statistics/results
Content-Type: application/json

{
    "userID" : "6435bd95c24a1f9badf71eee"
}